production:
  branch: production
  repository: https://github.com/openaustralia/alaveteli.git
  user: deploy
  deploy_to: /srv/www/production
  rails_env: production
  daemon_name: alaveteli-production

staging:
  branch: staging
  repository: https://github.com/openaustralia/alaveteli.git
  user: deploy
  deploy_to: /srv/www/staging
  rails_env: production
  daemon_name: alaveteli-staging
